FROM tensorflow/tensorflow:2.3.0-gpu-jupyter

RUN apt-get update && apt-get install -y \
    git

RUN git clone https://github.com/tensorflow/models.git 

RUN pip install contextlib2 Pillow tf_slim

COPY *.py /tf/

ENV PYTHONPATH "${PYTHONPATH}:/tf/models/research/slim"